import {useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import type {PdfDoc} from '../../db/models';
import type {PageTarget} from '../notes/page-links';
import {flushAllStrokes} from '../pdf/autosave';
import {buildPrompt,defaultTemplate,importResponse,saveTemplate,validateResponse,type AiResponse} from './bridge';
import './bridge.css';
export function AiBridge({noteId,current}:{noteId:string;current?:PageTarget}){
  const dialog=useRef<HTMLDialogElement>(null);const docs=useLiveQuery(()=>db.pdfDocs.where('noteId').equals(noteId).toArray(),[noteId])??[];
  const [docId,setDocId]=useState('');const [from,setFrom]=useState(1);const [to,setTo]=useState(1);const [template,setTemplate]=useState(defaultTemplate);const [prompt,setPrompt]=useState('');const [raw,setRaw]=useState('');const [preview,setPreview]=useState<AiResponse>();const [context,setContext]=useState<{doc?:PdfDoc;from:number;to:number}>();const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
  async function open(){setError('');setMessage('');try{await flushAllStrokes();const settings=await db.settings.get('main');setTemplate(settings?.promptTemplate||defaultTemplate);const selected=docs.find(d=>d.id===current?.pdfDocId)??docs[0];setDocId(selected?.id??'');setFrom(1);setTo(selected?.pages.length??1);setPrompt('');setPreview(undefined);setContext(undefined);setRaw('');dialog.current?.showModal();}catch{setError('ノートを保存できませんでした。');}}
  function reset(){setPreview(undefined);setContext(undefined);setPrompt('');setMessage('');}
  async function prepare(){setBusy(true);setError('');setMessage('');try{await flushAllStrokes();const doc=docs.find(d=>d.id===docId);const text=await db.textNotes.where('noteId').equals(noteId).first();const value=buildPrompt(template,text?.plainText??'',doc,from,to);setPrompt(value);setContext({doc,from,to});setPreview(undefined);try{await navigator.clipboard.writeText(value);setMessage('依頼文をコピーしました。ChatGPTなどに貼り付けてください。');}catch{setMessage('自動コピーできませんでした。下の依頼文を選択してコピーしてください。');}}catch(e){setError(e instanceof Error?e.message:'依頼文を作れませんでした。');}finally{setBusy(false);}}
  function validate(){setError('');setPreview(undefined);if(!context){setError('先に「AI用にコピー」で資料範囲を確定してください。');return;}try{setPreview(validateResponse(raw,context.doc,context.from,context.to));setMessage('内容を確認してから取り込んでください。');}catch(e){setError(e instanceof Error?e.message:'回答を確認できませんでした。');}}
  async function accept(){if(!preview||!context)return;setBusy(true);setError('');try{await importResponse(noteId,preview,context.doc,context.from,context.to);setMessage(`要約と${preview.questions.length}問を追加しました。「復習」から解けます。`);setPreview(undefined);setRaw('');}catch(e){setError(e instanceof Error?e.message:'取り込めませんでした。');}finally{setBusy(false);}}
  return <><button onClick={()=>void open()}>AI連携</button>{error&&!dialog.current?.open&&<span role="alert">{error}</span>}<dialog ref={dialog} className="ai-dialog" aria-label="AIとのコピー貼り付け連携" onCancel={e=>{if(busy)e.preventDefault();}}><div className="ai-heading"><h2>AI連携（コピー＆貼り付け）</h2><button disabled={busy} onClick={()=>dialog.current?.close()}>AI連携を閉じる</button></div><p>資料を外部AIに渡すときは、ご自身でコピーして貼り付けます。このアプリから外部への通信はありません。</p><label>AIに渡すPDF<select aria-label="AIに渡すPDF" value={docId} onChange={e=>{const doc=docs.find(d=>d.id===e.target.value);setDocId(e.target.value);setFrom(1);setTo(doc?.pages.length??1);reset();}}><option value="">テキストノートだけ</option>{docs.map(d=><option key={d.id} value={d.id}>{d.fileName}</option>)}</select></label>{docId&&<><div className="ai-range"><label>開始ページ<input aria-label="開始ページ" type="number" min="1" value={from} onChange={e=>{setFrom(Number(e.target.value));reset();}}/></label><label>終了ページ<input aria-label="終了ページ" type="number" min="1" value={to} onChange={e=>{setTo(Number(e.target.value));reset();}}/></label></div>{docs.find(d=>d.id===docId)?.textIndexed!==true&&<p>PDFの文字抽出が終わっていない場合は、検索用の文字抽出完了後にコピーしてください。画像・手書き文字は抽出されません。</p>}</>}<details><summary>設定：AIへの指示文を編集</summary><textarea aria-label="AI指示文テンプレート" value={template} maxLength={10000} onChange={e=>{setTemplate(e.target.value);reset();}}/><button disabled={busy} onClick={()=>void saveTemplate(template).then(()=>setMessage('指示文を保存しました。')).catch(e=>setError(e instanceof Error?e.message:'保存できませんでした。'))}>指示文を保存</button></details><button disabled={busy} onClick={()=>void prepare()}>AI用にコピー</button>{prompt&&<><p>{prompt.length.toLocaleString()}文字{prompt.length>20000?' · 長い場合はページ範囲を分けてください。':''}</p><textarea className="ai-prompt" aria-label="コピー用の依頼文" readOnly value={prompt} onFocus={e=>e.target.select()}/></>}<label>AIの回答を貼り付け<textarea aria-label="AIの回答を貼り付け" value={raw} maxLength={500000} onChange={e=>{setRaw(e.target.value);setPreview(undefined);}} placeholder="JSONまたはjsonコードブロックを貼り付け"/></label><button disabled={busy||!raw.trim()} onClick={validate}>回答を確認</button>{error&&<p className="ai-error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{preview&&<section className="ai-preview"><h3>取り込み内容の確認</h3><ul>{preview.summary.points.map((p,i)=><li key={i}>{p}</li>)}</ul><p>重要用語：{preview.summary.terms.join('、')||'なし'}</p>{preview.questions.map((q,i)=><details key={i}><summary>{i+1}. {q.question}</summary>{q.kind==='mcq'&&<ol>{q.choices.map(c=><li key={c}>{c}</li>)}</ol>}<p>正解：{q.answer}</p><p>{q.explanation}</p><small>根拠：{q.sourcePage===null?'テキストノート':`p.${q.sourcePage}`}</small></details>)}<button disabled={busy} onClick={()=>void accept()}>要約と{preview.questions.length}問を追加</button></section>}</dialog></>;
}
export function AiSummaryList({noteId}:{noteId:string}){const summaries=useLiveQuery(()=>db.aiSummaries.where('noteId').equals(noteId).toArray(),[noteId])??[];if(!summaries.length)return null;return <section className="ai-summaries" aria-label="取り込んだAI要約"><h3>AIから取り込んだ要約</h3><p>AIの内容は元の資料と照らし合わせて確認してください。</p>{summaries.sort((a,b)=>b.importedAt.localeCompare(a.importedAt)).map(s=><details key={s.id}><summary>{new Date(s.importedAt).toLocaleString('ja-JP')}の要約</summary><ul>{s.points.map((p,i)=><li key={i}>{p}</li>)}</ul><p>重要用語：{s.terms.join('、')||'なし'}</p></details>)}</section>;}
