import {useRef,useState,useEffect} from 'react';
import type {PdfDoc} from '../../db/models';
import {orderedMaterials,renameMaterial,reorderMaterials,trashMaterial} from './materials';
import {flushAllStrokes} from './autosave';
export function MaterialManager({docs,noteId}:{docs:PdfDoc[];noteId:string}){
  const [open,setOpen]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  const active=orderedMaterials(docs.filter(d=>!d.trashedAt)),trash=docs.filter(d=>d.trashedAt);
  async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await flushAllStrokes();await action();}catch(e){setError(e instanceof Error?e.message:'資料を変更できませんでした。');}finally{setBusy(false);}}
  function move(index:number,delta:number){const ids=active.map(d=>d.id);[ids[index],ids[index+delta]]=[ids[index+delta],ids[index]];void act(()=>reorderMaterials(noteId,ids));}
  return <><button className="material-manage" onClick={()=>setOpen(true)}>資料を整理</button><dialog ref={dialog} className="material-dialog" aria-label="資料を整理" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}><div className="dialog-heading"><h2>資料を整理</h2><button aria-label="資料の整理を閉じる" disabled={busy} onClick={()=>setOpen(false)}>×</button></div><p>名前と順番を変更できます。ごみ箱に移しても書き込みは残り、ここから戻せます。</p><div className="material-list">{active.map((doc,index)=><article key={doc.id}><form onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name'));void act(()=>renameMaterial(doc.id,name));}}><input key={doc.fileName} name="name" defaultValue={doc.fileName} aria-label={`${doc.fileName}の名前`} required maxLength={500}/><button disabled={busy}>名前を保存</button></form><div className="material-row-actions"><small>{doc.pages.length}ページ</small><button aria-label={`${doc.fileName}を上へ`} disabled={busy||index===0} onClick={()=>move(index,-1)}>↑</button><button aria-label={`${doc.fileName}を下へ`} disabled={busy||index===active.length-1} onClick={()=>move(index,1)}>↓</button><button disabled={busy} aria-label={`${doc.fileName}をごみ箱へ`} onClick={()=>void act(()=>trashMaterial(doc.id,true))}>ごみ箱へ</button></div></article>)}</div>{!active.length&&<p>資料はありません。画像やPDFを追加してください。</p>}<details className="material-trash"><summary>ごみ箱（{trash.length}）</summary>{trash.map(doc=><div key={doc.id}><span>{doc.fileName}</span><button disabled={busy} aria-label={`${doc.fileName}を復元`} onClick={()=>void act(()=>trashMaterial(doc.id,false))}>戻す</button></div>)}</details>{error&&<p role="alert" className="error">{error}</p>}</dialog></>;
}
