import {useEffect,useMemo,useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import type {TextBox} from '../../db/models';
import {TextBoxWriter} from './autosave';
import {transformTextBox,type Corner} from './text-box-geometry';
import {answerAt,fitAnswer,textAt,isTextDrag} from './answer-input';
import {normalizePoint,type Rotation} from './geometry';
import {textChanged} from './edit-history';

export function TextBoxes({historyRevision,onTextChange,docId,pageIndex,width,height,rotation,enabled,movable,onFinish,onEdit,quick=false,answerFont=18,onAnswerFont}:{historyRevision:number;onTextChange:(before:TextBox|undefined,after:TextBox|undefined)=>void;docId:string;pageIndex:number;width:number;height:number;rotation:Rotation;enabled:boolean;movable:boolean;quick?:boolean;answerFont?:number;onAnswerFont?:(size:number)=>void;onFinish:()=>void;onEdit:(answer?:boolean)=>void}){
  const boxes=useLiveQuery(()=>db.textBoxes.where('[pdfDocId+pageIndex]').equals([docId,pageIndex]).toArray(),[docId,pageIndex]);
  const [deleted,setDeleted]=useState<TextBox>();const [hidden,setHidden]=useState(new Set<string>());
  const [selected,setSelected]=useState<string>();const [preview,setPreview]=useState<TextBox>();const [status,setStatus]=useState<'saving'|'saved'|'error'>('saved');
  const [drafts,setDrafts]=useState<Record<string,TextBox>>({});const writer=useMemo(()=>new TextBoxWriter(setStatus),[]);
  const sessions=useRef(new Map<string,{before?:TextBox;after?:TextBox}>());const historyTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const record=useRef(onTextChange);record.current=onTextChange;
  function commit(){clearTimeout(historyTimer.current);for(const entry of sessions.current.values())if(textChanged(entry.before,entry.after))record.current(entry.before,entry.after);sessions.current.clear();window.dispatchEvent(new CustomEvent('text-edit-pending',{detail:{key:docId+'/'+pageIndex,active:false}}));}
  function track(id:string,after?:TextBox){window.dispatchEvent(new CustomEvent('text-edit-pending',{detail:{key:docId+'/'+pageIndex,active:true}}));const prior=sessions.current.get(id);sessions.current.set(id,{before:prior?prior.before:hidden.has(id)?undefined:display.get(id),after});clearTimeout(historyTimer.current);if(!drag.current)historyTimer.current=setTimeout(commit,1000);}
  useEffect(()=>{const finish=()=>{commit();setSelected(undefined);};window.addEventListener('finish-text-edit',finish);return()=>{window.removeEventListener('finish-text-edit',finish);commit();};},[]);
  useEffect(()=>{if(!enabled)commit();},[enabled]);
  useEffect(()=>{setDrafts({});setHidden(new Set());setSelected(undefined);setDeleted(undefined);setPreview(undefined);drag.current=undefined;},[historyRevision]);
  const enter=useRef<{id:string;caret:number}|undefined>(undefined);
  const layer=useRef<HTMLDivElement>(null);const drag=useRef<{box:TextBox;x:number;y:number;corner?:Corner;pointerId:number;moved?:boolean}|undefined>(undefined);
  useEffect(()=>{const flush=()=>void writer.flush().catch(()=>{});window.addEventListener('pagehide',flush);const visibility=()=>{if(document.hidden)flush();};document.addEventListener('visibilitychange',visibility);return()=>{window.removeEventListener('pagehide',flush);document.removeEventListener('visibilitychange',visibility);writer.dispose();};},[writer]);
  const canonicalW=rotation===90||rotation===270?height:width,canonicalH=rotation===90||rotation===270?width:height;
  const transform=rotation===90?`translate(${width}px,0) rotate(90deg)`:rotation===180?`translate(${width}px,${height}px) rotate(180deg)`:rotation===270?`translate(0,${height}px) rotate(270deg)`:'none';
  function save(box:TextBox){track(box.id,box);setDrafts(v=>({...v,[box.id]:box}));writer.queue(box);}
  function resizeAnswer(box:TextBox,text=box.text){const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(ctx)ctx.font=`${box.fontSize*canonicalW}px system-ui,sans-serif`;return fitAnswer(box,text,canonicalW/canonicalH,ctx?ctx.measureText(text.replace(/[\r\n]+/g,' ')).width/canonicalW:undefined);}
  function changeSize(box:TextBox,size:number){const next={...box,fontSize:size};save(box.kind==='answer'?resizeAnswer(next):next);commit();if(box.kind==='answer')onAnswerFont?.(Math.round(size*595));}
  function finishAnswer(element:HTMLTextAreaElement,id:string){commit();void writer.flush().then(()=>{setSelected(current=>current===id?undefined:current);element.blur();}).catch(()=>{});}
  function insertion(x:number,y:number):TextBox{const box:TextBox={id:crypto.randomUUID(),pdfDocId:docId,pageIndex,x,y,width:.32,height:.12,text:'',color:quick?'#2563eb':'#172033',fontSize:(quick?answerFont:16)/595};return quick?answerAt(box,x,y,canonicalW/canonicalH):textAt(box,x,y,canonicalW,canonicalH);}
  const display=new Map((boxes??[]).map(b=>[b.id,b]));for(const b of Object.values(drafts))display.set(b.id,b);
  return <div ref={layer} className={`text-box-layer ${enabled?'text-enabled':''}`} style={{width,height}} onPointerMove={e=>{if(!enabled||e.pointerType==='touch'||e.target!==e.currentTarget||drag.current){setPreview(undefined);return;}const [x,y]=normalizePoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect(),.5,rotation);setPreview(insertion(x,y));}} onPointerLeave={()=>setPreview(undefined)} onPointerDown={e=>{
    if(e.pointerType==='touch')return;
    if(!enabled||e.button!==0||e.target!==e.currentTarget)return;e.preventDefault();e.stopPropagation();
    const [x,y]=normalizePoint(e.clientX,e.clientY,e.currentTarget.getBoundingClientRect(),.5,rotation);
    const box=insertion(x,y);setPreview(undefined);save(box);setSelected(box.id);
  }}>
    <div className="text-box-plane" style={{width:canonicalW,height:canonicalH,transform}}>
      {enabled&&preview&&<div className="text-insertion-guide" aria-hidden="true" style={{left:preview.x*canonicalW+(quick?0:12),top:preview.y*canonicalH+(quick?0:12),fontSize:preview.fontSize*canonicalW}}><span>あ</span><i/></div>}
      {[...display.values()].filter(b=>!hidden.has(b.id)).map(box=><div key={box.id} className={`pdf-text-box ${enabled&&selected===box.id?'editable':''} ${box.kind==='answer'?'answer-box':''}`} style={{left:box.x*canonicalW,top:box.y*canonicalH,width:box.width*canonicalW,height:box.height*canonicalH}} onPointerDown={e=>e.stopPropagation()}>
        {enabled&&selected===box.id?<><div className="text-box-actions" onPointerDown={e=>e.stopPropagation()}><button aria-label="文字を小さく" onClick={()=>changeSize(box,Math.max(8/595,box.fontSize-2/595))}>A−</button><span>{Math.round(box.fontSize*595)}</span><button aria-label="文字を大きく" onClick={()=>changeSize(box,Math.min(72/595,box.fontSize+2/595))}>A＋</button><button aria-label="テキストボックスを削除" onClick={()=>{commit();track(box.id);setDeleted(box);setHidden(v=>new Set([...v,box.id]));setDrafts(v=>{const next={...v};delete next[box.id];return next;});writer.queue(null,box.id);commit();void writer.flush().catch(()=>{});}}>×</button></div>
        {(!quick?['n','e','s','w','nw','ne','sw','se'] as const:[]).map(handle=><div key={handle} role="button" aria-label={`テキスト枠${handle.length===2?'の角でサイズ変更':'線で移動'} ${handle}`} className={`text-frame-handle handle-${handle}`} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);commit();drag.current={box,x:e.clientX,y:e.clientY,pointerId:e.pointerId,corner:handle.length===2?handle as Corner:undefined};}} onPointerMove={e=>{const start=drag.current;if(!start||start.pointerId!==e.pointerId||!layer.current)return;e.preventDefault();e.stopPropagation();const rect=layer.current.getBoundingClientRect();const a=normalizePoint(start.x,start.y,rect,.5,rotation),b=normalizePoint(e.clientX,e.clientY,rect,.5,rotation);save(transformTextBox(start.box,b[0]-a[0],b[1]-a[1],start.corner));}} onPointerUp={()=>{drag.current=undefined;commit();void writer.flush().catch(()=>{});}} onPointerCancel={()=>{drag.current=undefined;commit();void writer.flush().catch(()=>{});}} onLostPointerCapture={()=>{drag.current=undefined;commit();void writer.flush().catch(()=>{});}}/>)}
        <textarea aria-label={`${pageIndex+1}ページのテキストボックス`} autoFocus={selected===box.id} onFocus={()=>setSelected(box.id)} onCompositionStart={()=>{enter.current=undefined;}} onPointerDown={()=>{enter.current=undefined;}} onKeyDown={e=>{
          if(e.nativeEvent.isComposing||e.nativeEvent.keyCode===229){enter.current=undefined;return;}
          if(quick){if(e.altKey&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();save(transformTextBox(box,e.key==='ArrowLeft'?-1/595:e.key==='ArrowRight'?1/595:0,e.key==='ArrowUp'?-1/842:e.key==='ArrowDown'?1/842:0));return;}if(e.key==='Enter'||e.key==='Tab'){e.preventDefault();finishAnswer(e.currentTarget,box.id);return;}if(e.key==='Escape'){e.preventDefault();finishAnswer(e.currentTarget,box.id);onFinish();return;}}

          if(e.key!=='Enter'||e.shiftKey){enter.current=undefined;return;}if(e.repeat){e.preventDefault();return;}
          const caret=e.currentTarget.selectionStart;
          if(enter.current?.id===box.id&&enter.current.caret===caret&&box.text[caret-1]==='\n'){
            e.preventDefault();const next={...box,text:box.text.slice(0,caret-1)+box.text.slice(caret)};save(next);commit();enter.current=undefined;
            void writer.flush().then(()=>{setSelected(undefined);onFinish();}).catch(()=>{});
          }else enter.current={id:box.id,caret:caret+1};
        }} wrap={box.kind==='answer'?'off':undefined} placeholder={quick?'答えを入力':'ここに入力'} value={box.text} style={{fontSize:box.fontSize*canonicalW,color:box.color}} onChange={e=>save(box.kind==='answer'?resizeAnswer(box,e.target.value):{...box,text:e.target.value})} onBlur={e=>{commit();void writer.flush().catch(()=>{});if(!e.currentTarget.closest('.pdf-text-box')?.contains(e.relatedTarget as Node|null))setSelected(current=>current===box.id?undefined:current);}}/></>:<div className="text-box-content" style={{fontSize:box.fontSize*canonicalW,color:box.color}}><span className={movable||enabled?'movable-text':''} role={movable||enabled?'button':undefined} tabIndex={movable||enabled?0:undefined} aria-label={enabled?'文字をクリックして編集・ドラッグして移動':movable?'テキストをドラッグして移動':undefined} onDoubleClick={()=>{if(movable){setSelected(box.id);onEdit(box.kind==='answer');}}} onPointerDown={e=>{if((!movable&&!enabled)||e.button!==0||e.pointerType==='touch')return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);commit();drag.current={box,x:e.clientX,y:e.clientY,pointerId:e.pointerId};}} onPointerMove={e=>{const start=drag.current;if(!start||start.pointerId!==e.pointerId||!layer.current)return;e.preventDefault();e.stopPropagation();if(!start.moved&&!isTextDrag(start.x,start.y,e.clientX,e.clientY))return;start.moved=true;const rect=layer.current.getBoundingClientRect(),a=normalizePoint(start.x,start.y,rect,.5,rotation),b=normalizePoint(e.clientX,e.clientY,rect,.5,rotation);save(transformTextBox(start.box,b[0]-a[0],b[1]-a[1]));}} onPointerUp={e=>{const start=drag.current;if(start?.pointerId!==e.pointerId)return;drag.current=undefined;commit();void writer.flush().catch(()=>{});if(enabled&&!start.moved)setSelected(box.id);}} onPointerCancel={()=>{drag.current=undefined;commit();void writer.flush().catch(()=>{});}} onLostPointerCapture={()=>{drag.current=undefined;commit();void writer.flush().catch(()=>{});}} onKeyDown={e=>{if(enabled&&(e.key==='Enter'||e.key===' ')){e.preventDefault();setSelected(box.id);return;}const movement={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]}[e.key];if(movable&&movement){e.preventDefault();e.stopPropagation();save(transformTextBox(box,movement[0],movement[1]));}}}>{box.text}</span></div>}
      </div>)}
    </div>
    {enabled&&deleted&&<button className="text-restore" onClick={()=>{setHidden(v=>{const next=new Set(v);next.delete(deleted.id);return next;});save(deleted);setDeleted(undefined);}}>削除したテキストを戻す</button>}
    {enabled&&status!=='saved'&&<span className="text-save-status" role="status">{status==='saving'?'文字を保存中…':<button onClick={()=>void writer.flush().catch(()=>{})}>文字の保存に失敗・再試行</button>}</span>}
  </div>;
}
