import {useEffect,useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import type {Exam,Note,Subject} from '../../db/models';
import {pageKey,type PageTarget} from '../notes/page-links';
import {dueCards} from '../review/scheduler';
import {calendarDays,recallStats,reviewStreak,uncheckedPages} from './dashboard';
import {saveExams,setPageChecked} from './repository';
import './home.css';
export default function HomeDashboard({onOpen,onReview}:{onOpen:(note:Note,target?:PageTarget)=>void;onReview:(subjectId?:string)=>void}){
  const data=useLiveQuery(async()=>{const [subjects,notes,cards,logs,docs,strokes,texts,checks]=await Promise.all([db.subjects.orderBy('order').toArray(),db.notes.toArray(),db.cards.toArray(),db.reviewLogs.toArray(),db.pdfDocs.toArray(),db.strokes.toArray(),db.textNotes.toArray(),db.pageChecks.toArray()]);return {subjects,notes,cards,logs,docs,strokes,texts,checks};});
  const [pageLimit,setPageLimit]=useState(5);
  const [now,setNow]=useState(Date.now()),[editing,setEditing]=useState<Subject>(),[exams,setExams]=useState<Exam[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showChecked,setShowChecked]=useState(false);const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(id);},[]);
  useEffect(()=>{if(editing)dialog.current?.showModal();else dialog.current?.close();},[editing]);
  if(!data)return <p>学習状況を読み込んでいます…</p>;
  const {subjects,notes,cards,logs,docs,strokes,texts,checks}=data;
  const due=dueCards(cards,now),noteById=new Map(notes.map(n=>[n.id,n])),upcoming=subjects.flatMap(subject=>subject.exams.map(exam=>({subject,exam,days:calendarDays(exam.date,new Date(now))}))).filter(e=>Number.isFinite(e.days)&&e.days>=0).sort((a,b)=>a.days-b.days);
  const unchecked=uncheckedPages(notes,docs,strokes,texts,checks),recent=notes.filter(n=>n.lastOpenedAt).sort((a,b)=>Date.parse(b.lastOpenedAt!)-Date.parse(a.lastOpenedAt!)).slice(0,5),stats=recallStats(subjects,notes,cards,logs);
  const run=async(action:()=>Promise<void>)=>{setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{setBusy(false);}};
  return <div className="home-dashboard">{error&&<p role="alert">{error}</p>}
    <section className="home-section"><h2>今日の復習 <span>{due.length}枚</span></h2><button onClick={()=>onReview()} disabled={!due.length}>復習を始める</button>{subjects.map(s=>{const count=due.filter(c=>noteById.get(c.noteId)?.subjectId===s.id).length;return <div className="home-row" key={s.id}><span>{s.icon} {s.name}</span><button disabled={!count} onClick={()=>onReview(s.id)}>{count}枚を復習</button></div>;})}{!cards.filter(c=>c.kind!=='mask').length&&<p>授業の「復習カード」から問題を作成できます。</p>}</section>
    <section className="home-section"><h2>試験カウントダウン</h2>{upcoming.length?upcoming.map((e,i)=><div className="home-row" key={`${e.subject.id}/${i}`}><div><strong>{e.subject.icon} {e.subject.name} · {e.exam.name}</strong><small>{e.exam.date}</small></div><b>{e.days===0?'今日':`あと${e.days}日`}</b></div>):<p>これからの試験は登録されていません。</p>}<div className="home-exam-buttons">{subjects.map(s=><button key={s.id} onClick={()=>{setError('');setExams(s.exams.map(e=>({...e})));setEditing(s);}}>{s.icon} {s.name}の試験</button>)}</div></section>
    <section className="home-section"><h2>最近開いた授業</h2>{recent.length?recent.map(n=><button className="home-note" key={n.id} onClick={()=>onOpen(n)}>{subjects.find(s=>s.id===n.subjectId)?.name} · 第{n.sessionNumber}回 {n.title}<small>最終表示 {new Date(n.lastOpenedAt!).toLocaleString('ja-JP')}</small></button>):<p>授業を開くと、ここに表示されます。</p>}</section>
    <section className="home-section"><h2>未チェックのPDFページ <span>{unchecked.length}ページ</span></h2><p>直近に作成した5授業のうち、手書き・ページリンク・確認済みの印がない元PDFページです。</p>{unchecked.slice(0,pageLimit).map(({note,doc,target})=><div className="home-row" key={`${doc.id}/${target.pageKey}`}><button className="home-page" onClick={()=>onOpen(note,target)}>第{note.sessionNumber}回 {note.title}<small>{doc.fileName} · p.{target.pageIndex+1}</small></button><button disabled={busy} onClick={()=>void run(()=>setPageChecked(target,true))}>確認済みにする</button></div>)}{unchecked.length>pageLimit&&<button onClick={()=>setPageLimit(v=>v+20)}>さらに20ページを表示（残り{unchecked.length-pageLimit}）</button>}{!unchecked.length&&<p>未チェックのページはありません。</p>}<button onClick={()=>setShowChecked(v=>!v)}>{showChecked?'確認済み一覧を閉じる':`確認済み一覧（${checks.length}）`}</button>{showChecked&&checks.map(c=>{const doc=docs.find(d=>d.id===c.pdfDocId),note=doc?noteById.get(doc.noteId):undefined,page=doc?.pages[c.pageIndex];if(!doc||!note||!page)return null;const target={pdfDocId:doc.id,pageKey:pageKey(page,c.pageIndex),pageIndex:c.pageIndex};return <div className="home-row" key={c.id}><button onClick={()=>onOpen(note,target)}>{note.title} · p.{c.pageIndex+1}</button><button disabled={busy} onClick={()=>void run(()=>setPageChecked(target,false))}>確認済みを解除</button></div>;})}</section>
    <section className="home-section"><h2>学習の記録</h2><p className="home-streak">復習の継続 <strong>{reviewStreak(logs,new Date(now))}日</strong></p><p>今日または昨日まで続けて復習した日数です。</p><h3>科目別・自己評価の正答率</h3><p>「正解」「簡単」の評価を正答として集計します。自動採点の正答率とは異なります。</p>{stats.map(s=><div className="home-row" key={s.subject.id}><span>{s.subject.icon} {s.subject.name}</span><span>{s.total?`${Math.round(s.recalled/s.total*100)}%（${s.recalled}/${s.total}回）`:'まだ評価がありません'}</span></div>)}</section>
    <dialog aria-labelledby="home-exam-title" className="home-exam-dialog" ref={dialog} onCancel={event=>{if(busy)event.preventDefault();else setEditing(undefined);}}><h2 id="home-exam-title">{editing?.name}の試験</h2><p>試験名と日付を登録してください。終了した試験もここで管理できます。</p>{exams.map((e,i)=><div className="home-exam-edit" key={i}><label>試験名 {i+1}<input value={e.name} maxLength={100} onChange={event=>setExams(exams.map((v,j)=>j===i?{...v,name:event.target.value}:v))}/></label><label>試験日 {i+1}<input type="date" value={e.date} onChange={event=>setExams(exams.map((v,j)=>j===i?{...v,date:event.target.value}:v))}/></label><button disabled={busy} onClick={()=>setExams(exams.filter((_,j)=>j!==i))}>この試験を削除</button></div>)}<button disabled={busy} onClick={()=>setExams([...exams,{name:'',date:''}])}>＋ 試験を追加</button>{error&&<p role="alert">{error}</p>}<div className="home-dialog-actions"><button disabled={busy} onClick={()=>setEditing(undefined)}>キャンセル</button><button disabled={busy} onClick={()=>void run(async()=>{if(editing){await saveExams(editing.id,exams);setEditing(undefined);}})}>試験を保存</button></div></dialog>
  </div>;
}
