import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import type {Card,PdfDoc} from '../../db/models';
import {pageKey,resolvePage,type PageTarget} from '../notes/page-links';
import {saveCard,deleteCard} from './repository';
import {dueAt} from './scheduler';
import './review.css';
export function cardSource(card:Card,docs:PdfDoc[]):PageTarget|undefined{const doc=docs.find(d=>d.id===card.pdfDocId);if(!doc)return;const key=card.sourcePageKey??(doc.pages[card.pageIndex??-1]?pageKey(doc.pages[card.pageIndex!],card.pageIndex!):undefined);if(!key)return;const target={pdfDocId:doc.id,pageKey:key,pageIndex:card.pageIndex??0},index=resolvePage(doc,target);return index>=0?{...target,pageIndex:index}:undefined;}
export function CardManager({noteId,current,onJump}:{noteId:string;current?:PageTarget;onJump:(target:PageTarget)=>void}){
  const cards=useLiveQuery(()=>db.cards.where('noteId').equals(noteId).toArray(),[noteId])??[],docs=useLiveQuery(()=>db.pdfDocs.where('noteId').equals(noteId).toArray(),[noteId])??[];
  const [open,setOpen]=useState(false),[editing,setEditing]=useState<Card|'new'>(),[remove,setRemove]=useState<Card>(),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');try{const source=String(f.get('source'));await saveCard({id:editing&&editing!=='new'?editing.id:undefined,noteId,question:String(f.get('question')),answer:String(f.get('answer')),explanation:String(f.get('explanation')),source:source==='current'?current:undefined,keepSource:source==='keep'});setEditing(undefined);}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{setBusy(false);}}
  return <><button className="secondary" onClick={()=>{setOpen(true);setError('');}}>復習カード（{cards.filter(c=>c.kind!=='mask').length}）</button><dialog ref={dialog} className="review-dialog" aria-label="授業の復習カード" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}><div className="dialog-heading"><h2>授業の復習カード</h2><button aria-label="カード一覧を閉じる" disabled={busy} onClick={()=>setOpen(false)}>×</button></div><p className="review-hint">問題と答えを登録すると、今すぐ復習できます。評価に合わせて次回の期限が決まります。</p>{!editing&&<button className="primary" onClick={()=>setEditing('new')}>＋ カードを作成</button>}
    {editing&&<form key={editing==='new'?'new':editing.id} onSubmit={e=>void submit(e)}><label>問題<textarea name="question" aria-label="カードの問題" autoFocus required maxLength={2000} defaultValue={editing==='new'?'':editing.question}/></label><label>答え<textarea name="answer" aria-label="カードの答え" required maxLength={5000} defaultValue={editing==='new'?'':editing.answer}/></label><label>補足・解説（任意）<textarea name="explanation" aria-label="カードの解説" maxLength={5000} defaultValue={editing==='new'?'':editing.explanation}/></label><label>PDFの参照先<select name="source" aria-label="カードの参照先" defaultValue={editing!=='new'&&editing.pdfDocId?'keep':'none'}>{editing!=='new'&&editing.pdfDocId&&<option value="keep">登録済みのページを保持</option>}<option value="none">紐づけない</option><option value="current" disabled={!current}>現在のPDFページ{current?` p.${current.pageIndex+1}`:''}</option></select></label><div className="dialog-actions"><button type="button" disabled={busy} onClick={()=>setEditing(undefined)}>キャンセル</button><button className="primary" disabled={busy}>カードを保存</button></div></form>}
    {!editing&&<div className="review-card-list">{cards.filter(c=>c.kind!=='mask').map(c=>{const source=cardSource(c,docs),due=dueAt(c);return <article key={c.id}><strong>{c.question||'問題未設定'}</strong><small>{Number.isFinite(due)?`次回：${formatDue(due)}`:'復習日が不正です。カードを再作成してください。'}</small><div>{source&&<button onClick={()=>{setOpen(false);onJump(source);}}>元のPDF p.{source.pageIndex+1}</button>}<button onClick={()=>setEditing(c)} disabled={c.kind!=='short'}>編集</button><button className="text-danger" onClick={()=>setRemove(c)}>削除</button></div></article>;})}{!cards.some(c=>c.kind!=='mask')&&<p className="review-hint">カードはまだありません。</p>}</div>}
    {remove&&<div className="review-delete" role="alert"><p>「{remove.question}」と復習履歴を削除します。取り消せません。</p><button disabled={busy} onClick={()=>setRemove(undefined)}>キャンセル</button><button className="danger" disabled={busy} onClick={()=>{setBusy(true);void deleteCard(remove.id).then(()=>setRemove(undefined)).catch(()=>setError('削除できませんでした。')).finally(()=>setBusy(false));}}>削除する</button></div>}{error&&<p className="error" role="alert">{error}</p>}</dialog></>;
}
export function formatDue(time:number){return new Intl.DateTimeFormat('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(time);}
