import {useEffect,useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import type {Card,Note} from '../../db/models';
import type {PageTarget} from '../notes/page-links';
import {dueCards,dueAt,intervalLabel,rateSchedule,ratings} from './scheduler';
import {reviewCard,undoReview} from './repository';
import {assessChoice} from './choices';
import {cardSource,formatDue} from './CardManager';
export function ReviewPanel({onOpen,request}:{onOpen:(note:Note,target?:PageTarget)=>void;request?:{id:string;subjectId?:string}}){
  const cards=useLiveQuery(()=>db.cards.toArray())??[],notes=useLiveQuery(()=>db.notes.toArray())??[],subjects=useLiveQuery(()=>db.subjects.orderBy('order').toArray())??[],docs=useLiveQuery(()=>db.pdfDocs.toArray())??[];
  const [open,setOpen]=useState(false),[scope,setScope]=useState('all'),[lesson,setLesson]=useState('all'),[clock,setClock]=useState(Date.now()),[queue,setQueue]=useState<Card[]>([]),[position,setPosition]=useState(0),[started,setStarted]=useState(false),[revealed,setRevealed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[completed,setCompleted]=useState(0),[last,setLast]=useState<{id:string;card:Card;position:number;due:string}>();
  const [choice,setChoice]=useState<{selected:string;correct:boolean}>();
  useEffect(()=>{if(request){setScope(request.subjectId??'all');setLesson('all');setClock(Date.now());setStarted(false);setError('');setOpen(true);}},[request]);
  useEffect(()=>setChoice(undefined),[position,started]);
  const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),60000);return()=>clearInterval(timer);},[]);
  useEffect(()=>setClock(Date.now()),[cards.length]);
  const filtered=cards.filter(c=>{const note=notes.find(n=>n.id===c.noteId);return note&&(scope==='all'||note.subjectId===scope)&&(lesson==='all'||note.id===lesson);});const due=dueCards(filtered,clock),card=queue[position],note=notes.find(n=>n.id===card?.noteId),source=card?cardSource(card,docs):undefined;
  const nextDue=filtered.filter(c=>c.kind!=='mask'&&dueAt(c)>clock&&Number.isFinite(dueAt(c))).sort((a,b)=>dueAt(a)-dueAt(b))[0];
  function start(){setQueue(dueCards(filtered,Date.now()));setPosition(0);setCompleted(0);setLast(undefined);setRevealed(false);setError('');setStarted(true);}
  async function rate(value:1|2|3|4,advance=true){if(!card||busy)return;setBusy(true);setError('');try{const saved=await reviewCard(card,value);setLast({...saved,card,position});if(advance)setPosition(v=>v+1);setCompleted(v=>v+1);if(advance)setRevealed(false);return true;}catch(e){setError(e instanceof Error?e.message:'評価を保存できませんでした。');}finally{setBusy(false);}}
  async function undo(){if(!last||busy)return;setBusy(true);setError('');try{await undoReview(last.id);setPosition(last.position);setChoice(undefined);setRevealed(false);setCompleted(v=>Math.max(0,v-1));setLast(undefined);}catch(e){setError(e instanceof Error?e.message:'戻せませんでした。');}finally{setBusy(false);}}
  async function choose(selected:string){if(!card||busy||revealed)return;try{const correct=assessChoice(card,selected);if(!correct){if(!await rate(1,false))return;}setChoice({selected,correct});setRevealed(true);}catch(e){setError(e instanceof Error?e.message:'採点できませんでした。');}}
  return <><button className="nav-home" onClick={()=>{setOpen(true);setClock(Date.now());setStarted(false);setError('');}}>↻ <span>復習</span><span className="count">{dueCards(cards,clock).length}</span></button><dialog className="review-dialog" ref={dialog} aria-label="復習セッション" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}><div className="dialog-heading"><h2>復習</h2><button aria-label="復習を閉じる" disabled={busy} onClick={()=>setOpen(false)}>×</button></div>
    {!started?<><p className="review-hint">期限になったカードを復習します。授業画面の「復習カード」から問題を作れます。</p><div className="review-filters"><label>科目<select aria-label="復習する科目" value={scope} onChange={e=>{setScope(e.target.value);setLesson('all');}}><option value="all">全科目</option>{subjects.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>授業<select aria-label="復習する授業" value={lesson} onChange={e=>setLesson(e.target.value)}><option value="all">すべての授業</option>{notes.filter(n=>scope==='all'||n.subjectId===scope).map(n=><option key={n.id} value={n.id}>第{n.sessionNumber}回・{n.title}</option>)}</select></label></div><div className="review-ready"><strong>{due.length}</strong><span>枚が復習できます</span></div><button className="primary" disabled={!due.length} onClick={start}>復習を始める</button>{nextDue&&<p className="review-hint">次の期限：{formatDue(dueAt(nextDue))}</p>}{!filtered.some(c=>c.kind!=='mask')&&<p className="review-hint">授業を開いて、最初のカードを作成してください。</p>}</>:card?<><p className="review-hint">{position+1} / {queue.length} · {note?.title??'授業が削除されています'}</p><div className="review-question"><small>問題</small><p>{card.question}</p>{card.kind==='mcq'&&card.choices?.map((option,i)=><button className="review-choice" key={i} disabled={busy||revealed} onClick={()=>void choose(option)}>{i+1}. {option}{choice?.selected===option?'（選択）':''}</button>)}</div>{!revealed?(card.kind==='mcq'?<p className="review-hint">選択肢を押して答えてください。不正解は「もう一度」として記録します。</p>:<button className="primary reveal-answer" onClick={()=>setRevealed(true)}>答えを見る</button>):<><div className="review-answer">{choice&&<p role="status">{choice.correct?'正解です。':'不正解です。「もう一度」で記録しました。'}</p>}<small>答え</small><p>{card.answer}</p>{card.explanation&&<><small>解説</small><p>{card.explanation}</p></>}</div>{choice?.correct!==false&&<><p className="review-hint">思い出せた度合いを選んでください。</p><div className="rating-buttons">{ratings.map(r=>{let hint='';try{hint=intervalLabel(Date.parse(String(rateSchedule(card.fsrs,r.value).card.due)));}catch{/* 評価時に保存エラーを表示 */}return <button key={r.value} className={`rating rating-${r.value}`} disabled={busy} onClick={()=>void rate(r.value)}>{r.label}<small>{hint}</small></button>;})}</div></>}</>}{source&&note&&<button className="secondary" disabled={busy} onClick={()=>{setOpen(false);onOpen(note,source);}}>元のPDF p.{source.pageIndex+1}を開く</button>}<button disabled={busy} onClick={()=>{setPosition(v=>v+1);setRevealed(false);}}>{choice?.correct===false?'次の問題へ':'今回はスキップ'}</button></>:<div className="review-finished"><h3>この回の復習が終わりました</h3><p>{completed}枚を評価しました。</p><p className="review-hint">「もう一度」などで短い期限になったカードは、その時刻以降に再び復習できます。</p><button className="primary" onClick={()=>{setClock(Date.now());setStarted(false);}}>期限の一覧へ戻る</button></div>}
    {started&&last&&<div className="review-last"><span>直前のカードの次回：{formatDue(Date.parse(last.due))}</span><button disabled={busy} onClick={()=>void undo()}>直前の評価を取り消す</button></div>}{error&&<p className="error" role="alert">{error}</p>}</dialog></>;
}
