import {it,expect} from 'vitest';
import {StudyDatabase} from '../../db/database';
import {newSchedule,rateSchedule,readSchedule,dueCards,dueAt} from './scheduler';
import {saveCard,reviewCard,undoReview,deleteCard} from './repository';
import {snapshot,createArchive,readArchive} from '../backup/archive';
import {restore} from '../backup/restore';
const now=new Date('2026-10-02T00:00:00Z');
async function setup(){const database=new StudyDatabase(crypto.randomUUID());await database.subjects.put({id:'s',name:'数学',color:'#2563eb',icon:'📘',order:0,exams:[],createdAt:now.toISOString()});await database.notes.put({id:'n',subjectId:'s',title:'一次関数',sessionNumber:1,order:0,createdAt:now.toISOString(),updatedAt:now.toISOString()});return database;}
it('FSRSの4評価で期限を決め、日付をJSONから再現する',()=>{const initial=newSchedule(now);expect(readSchedule(initial).reps).toBe(0);const again=rateSchedule(initial,1,now),good=rateSchedule(initial,3,now),easy=rateSchedule(initial,4,now);expect(Date.parse(String(again.card.due))).toBeGreaterThan(now.getTime());expect(Date.parse(String(easy.card.due))).toBeGreaterThan(Date.parse(String(good.card.due)));expect(readSchedule(JSON.parse(JSON.stringify(easy.card))).reps).toBe(1);expect(()=>readSchedule({due:'壊れた日付'})).toThrow();});
it('カードの編集は履歴を維持し、評価と履歴を保存、直前評価を取り消す',async()=>{const database=await setup(),id=await saveCard({noteId:'n',question:'傾きは？',answer:'xの係数',explanation:''},database);const card=(await database.cards.get(id))!;card.fsrs=newSchedule(now);await database.cards.put(card);const saved=await reviewCard(card,3,now,database);expect((await database.cards.get(id))?.fsrs.reps).toBe(1);expect(await database.reviewLogs.count()).toBe(1);await saveCard({id,noteId:'n',question:'傾きとは？',answer:'変化の割合',explanation:''},database);expect((await database.cards.get(id))?.fsrs.reps).toBe(1);await undoReview(saved.id,database);expect((await database.cards.get(id))?.fsrs).toEqual(card.fsrs);expect(await database.reviewLogs.count()).toBe(0);await database.delete();});
it('同じ状態の二重評価を拒否し、削除時は履歴も削除する',async()=>{const database=await setup(),id=await saveCard({noteId:'n',question:'問題',answer:'答え',explanation:''},database),card=(await database.cards.get(id))!;await reviewCard(card,1,new Date(),database);await expect(reviewCard(card,4,new Date(),database)).rejects.toThrow('別の画面');expect(await database.reviewLogs.count()).toBe(1);await deleteCard(id,database);expect(await database.cards.count()).toBe(0);expect(await database.reviewLogs.count()).toBe(0);await database.delete();});
it('期限カードを順序付け、赤シートカードと不正な日付を含めない',async()=>{const database=await setup(),id=await saveCard({noteId:'n',question:'問題',answer:'答え',explanation:''},database),card=(await database.cards.get(id))!;card.fsrs=newSchedule(now);expect(dueCards([card,{...card,id:'mask',kind:'mask'},{...card,id:'bad',fsrs:{}}],now.getTime())).toHaveLength(1);expect(dueAt({...card,fsrs:{}})).toBe(Infinity);expect(dueCards([card],now.getTime()-1)).toHaveLength(0);await database.delete();});
it('復習カードと取り消し情報をZIPからマージ復元して使える',async()=>{const database=await setup(),id=await saveCard({noteId:'n',question:'傾き',answer:'変化の割合',explanation:''},database),card=(await database.cards.get(id))!;const saved=await reviewCard(card,4,new Date(),database);const backup=await readArchive(await createArchive(await snapshot(undefined,database),()=>{}));await restore(backup,'merge',database);const copy=(await database.cards.toArray()).find(c=>c.id!==id)!;expect(readSchedule(copy.fsrs).reps).toBe(1);const log=(await database.reviewLogs.where('cardId').equals(copy.id).first())!;expect(log.previousFsrs).toEqual(card.fsrs);await undoReview(log.id,database);expect(readSchedule((await database.cards.get(copy.id))!.fsrs).reps).toBe(0);expect(await database.reviewLogs.get(saved.id)).toBeDefined();await database.delete();});
