import {useEffect,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {safety,autoPreferences,automaticBackup,waitAutomaticBackup,directoryPicker,type Checkpoint} from './automatic';
import {createArchive,readArchive,type PreparedBackup} from './archive';
export function AutoBackup({onPrepared}:{onPrepared:(backup:PreparedBackup)=>void}){
  const preferences=useLiveQuery(()=>safety.preferences.get('main')),records=useLiveQuery(()=>safety.checkpoints.orderBy('createdAt').reverse().toArray())??[];
  const [busy,setBusy]=useState(false),[status,setStatus]=useState('変更があれば5分ごとに保存します。'),[error,setError]=useState(''),[download,setDownload]=useState<{url:string;name:string}>();
  useEffect(()=>()=>{if(download)URL.revokeObjectURL(download.url);},[download]);
  useEffect(()=>{const run=()=>{if(document.hidden)return;void automaticBackup().then(message=>{setStatus(message);setError('');}).catch(e=>setError(e instanceof Error?e.message:'自動バックアップに失敗しました。空き容量を確認してください。'));};const first=setTimeout(run,30000),timer=setInterval(run,5*60*1000);const visible=()=>{if(!document.hidden)run();};document.addEventListener('visibilitychange',visible);return()=>{clearTimeout(first);clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[]);
  async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action();}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setError(e instanceof Error?e.message:'バックアップできませんでした。');}finally{setBusy(false);}}
  async function folder(){if(!directoryPicker)return;const handle=await directoryPicker({mode:'readwrite',id:'study-notes-backup'});const settings=await autoPreferences();await safety.preferences.put({...settings,enabled:true,folder:handle,folderId:crypto.randomUUID(),folderSignature:undefined});await waitAutomaticBackup();setStatus(await automaticBackup(true));}
  async function allow(){const settings=await autoPreferences();if(settings.folder&&await settings.folder.requestPermission({mode:'readwrite'})==='granted')setStatus(await automaticBackup(true));else setStatus('フォルダ保存は許可されませんでした。ブラウザ内の復元ポイントは利用できます。');}
  async function saved(record:Checkpoint,restore=false){const bytes=await createArchive(record.snapshot,setStatus);if(restore){onPrepared(await readArchive(bytes));setStatus('復元方法を下で選んでください。まだ学習データは変更していません。');}else{setDownload({url:URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/zip'})),name:`学習ノート_自動保存_${record.createdAt.replace(/[:.]/g,'-')}.zip`});}}
  return <section className="auto-backup"><h3>自動バックアップ</h3><label className="auto-backup-switch"><input type="checkbox" checked={preferences?.enabled??true} disabled={busy} onChange={e=>{const enabled=e.target.checked;void act(async()=>{await safety.preferences.put({...await autoPreferences(),enabled});setStatus(enabled?'自動バックアップを開始しました。':'自動バックアップを停止しました。');});}}/>5分ごとに変更を確認して保存</label><p>ブラウザ内に直近3回の復元ポイントを残します。サイトデータを消すと一緒に消えるため、PCでは保存フォルダも指定してください。アプリを開いている間に動作します。</p><div className="auto-backup-actions"><button disabled={busy} onClick={()=>void act(async()=>setStatus(await automaticBackup(true)))}>今すぐバックアップ</button>{directoryPicker&&<button disabled={busy} onClick={()=>void act(folder)}>{preferences?.folder?'保存フォルダを変更':'PCの保存フォルダを指定'}</button>}{preferences?.folder&&<><button disabled={busy} onClick={()=>void act(allow)}>保存を再許可</button><button disabled={busy} onClick={()=>void act(async()=>{await safety.preferences.put({...await autoPreferences(),folder:undefined,folderSignature:undefined});setStatus('フォルダへの自動保存を停止しました。保存したZIPは残ります。');})}>フォルダ保存を停止</button></>}</div>{preferences?.folder&&<p>保存先：{preferences.folder.name} · ZIPも3回分を交代で更新{preferences.folderSavedAt&&` · 最終保存 ${new Date(preferences.folderSavedAt).toLocaleString('ja-JP')}`}</p>}{!directoryPicker&&<p>このブラウザではフォルダへの自動保存に対応していません。復元ポイントのZIP保存を利用できます。</p>}<p role="status">{busy?'バックアップを処理中…':status}</p>{error&&<p role="alert" className="error">{error}</p>}<div className="checkpoint-list">{records.map(record=><div key={record.id}><span>{new Date(record.createdAt).toLocaleString('ja-JP')}<small>{record.snapshot.data.notes.length}授業 · {record.snapshot.pdfs.length}資料</small></span><button disabled={busy} onClick={()=>void act(()=>saved(record))}>ZIPを用意</button><button disabled={busy} onClick={()=>void act(()=>saved(record,true))}>復元を準備</button></div>)}</div>{download&&<a className="pdf-download" href={download.url} download={download.name}>復元ポイントのZIPを保存</a>}</section>;
}
