import {useEffect,useRef,useState} from 'react';
import {useLiveQuery} from 'dexie-react-hooks';
import {db} from '../../db/database';
import {flushAllStrokes} from '../pdf/autosave';
import {snapshot,createArchive,readArchive,archiveEntries,type PreparedBackup} from './archive';
import {restore,backupDue} from './restore';
import './backup.css';
export function BackupPanel({onRestored}:{onRestored:()=>void}){
  const subjects=useLiveQuery(()=>db.subjects.orderBy('order').toArray())??[],settings=useLiveQuery(()=>db.settings.get('main'));
  const [open,setOpen]=useState(false),[scope,setScope]=useState('all'),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
  const [download,setDownload]=useState<{url:string;name:string;size:number;all:boolean;entries:{name:string;size:number}[]}>(),[requested,setRequested]=useState(false),[prepared,setPrepared]=useState<PreparedBackup>(),[mode,setMode]=useState<'merge'|'replace'>('merge'),[confirm,setConfirm]=useState(false),[storage,setStorage]=useState('保存状態を確認中');
  const dialog=useRef<HTMLDialogElement>(null),file=useRef<HTMLInputElement>(null);
  useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
  useEffect(()=>()=>{if(download)URL.revokeObjectURL(download.url);},[download]);
  useEffect(()=>{void(async()=>{try{if(!navigator.storage?.persist){setStorage('このブラウザは永続保存の要求に未対応');return;}const persisted=await navigator.storage.persisted()||await navigator.storage.persist();setStorage(persisted?'ブラウザの永続保存が許可されています':'永続保存は未許可。ZIPを定期的に保存してください');}catch{setStorage('永続保存を確認できません。ZIPを定期的に保存してください');}})();},[]);
  async function exportZip(){setBusy(true);setError('');setRequested(false);setDownload(undefined);try{await flushAllStrokes();const s=await snapshot(scope==='all'?undefined:scope);const bytes=await createArchive(s,setProgress);setDownload({url:URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/zip'})),name:`学習ノート_${scope==='all'?'全データ':'科目'}_${new Date().toISOString().slice(0,10)}.zip`,size:bytes.length,all:scope==='all',entries:archiveEntries(bytes)});setProgress(`ZIPの準備ができました：${s.data.subjects.length}科目・${s.data.notes.length}授業・${s.pdfs.length}PDF`);}catch(e){setError(e instanceof Error?e.message:'ZIPを作成できませんでした。');setProgress('');}finally{setBusy(false);}}
  async function loadZip(selected?:File){if(!selected)return;setBusy(true);setError('');setPrepared(undefined);setConfirm(false);setProgress('ZIPの内容とPDFを検証しています…');try{if(selected.size>250*1024*1024)throw new Error('ZIPは250MB以下にしてください。');const backup=await readArchive(new Uint8Array(await selected.arrayBuffer()));setPrepared(backup);setMode('merge');setProgress('内容の検証が完了しました。まだデータは変更していません。');}catch(e){setError(e instanceof Error?e.message:'ZIPを読み込めませんでした。');setProgress('');}finally{setBusy(false);if(file.current)file.current.value='';}}
  async function importZip(){if(!prepared)return;setBusy(true);setError('');try{await flushAllStrokes();await (await import('../search/pdf-index')).waitForPdfIndexes();onRestored();await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));await flushAllStrokes();await restore(prepared,mode);setPrepared(undefined);setConfirm(false);setProgress('復元が完了しました。');}catch(e){setError(e instanceof Error?e.message:'復元できませんでした。元のデータを保持しています。');}finally{setBusy(false);}}
  async function acknowledge(){try{const current=await db.settings.get('main');await db.settings.put(current?{...current,lastExportAt:new Date().toISOString()}:{id:'main',maskColor:'#ef4444',promptTemplate:'',penPresets:[],theme:'light',lastExportAt:new Date().toISOString()});setProgress('全データのバックアップ日時を記録しました。');setRequested(false);}catch{setError('バックアップ日時を記録できませんでした。');}}
  return <><button className="nav-home" onClick={()=>setOpen(true)}>↓ <span>バックアップ</span>{subjects.length>0&&backupDue(settings?.lastExportAt)&&<span className="backup-dot" aria-label="バックアップ推奨">●</span>}</button>
    {subjects.length>0&&backupDue(settings?.lastExportAt)&&<div className="backup-reminder">{settings?.lastExportAt?'前回の全データ保存から7日以上経過しています。':'まだ全データのバックアップがありません。'}<button onClick={()=>setOpen(true)}>ZIPを保存</button></div>}
    <dialog className="backup-dialog" ref={dialog} aria-label="バックアップと復元" onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}><div className="dialog-heading"><h2>バックアップと復元</h2><button aria-label="バックアップを閉じる" disabled={busy} onClick={()=>setOpen(false)}>×</button></div><p className="backup-storage">{storage}</p><section><h3>ZIPに保存</h3><p>復元用データ・元PDF・書き込みPDF・テキストノートをまとめます。</p><label>保存する範囲<select aria-label="保存する範囲" value={scope} disabled={busy} onChange={e=>setScope(e.target.value)}><option value="all">全データ</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><button className="primary" disabled={busy} onClick={()=>void exportZip()}>ZIPを作成</button>{download&&<div className="backup-download"><a className="pdf-download" href={download.url} download={download.name} onClick={()=>setRequested(true)}>ZIPを保存</a><small>{(download.size/1024/1024).toFixed(2)}MB</small>{requested&&download.all&&<button className="secondary" onClick={()=>void acknowledge()}>保存できました</button>}<small>{download.all?'ファイルの保存後に「保存できました」を押すと、バックアップ日時を記録します。':'科目別の保存では、全データのバックアップ日時は更新しません。'}</small><details className="archive-entries"><summary>ZIPの内容（{download.entries.length}ファイル）</summary><ul>{download.entries.map(entry=><li key={entry.name}>{entry.name}<small>{(entry.size/1024).toFixed(1)}KB</small></li>)}</ul></details></div>}</section><section><h3>ZIPから復元</h3><p>このアプリで作ったバックアップを選んでください。最大250MB。</p><input ref={file} className="file-input" type="file" accept=".zip,application/zip" aria-label="バックアップZIP" onChange={e=>void loadZip(e.target.files?.[0])}/><button className="secondary" disabled={busy} onClick={()=>file.current?.click()}>バックアップZIPを選ぶ</button>{prepared&&<div className="restore-preview"><strong>{prepared.manifest.scope==='all'?'全データ':'科目別'}のバックアップ</strong><p>{prepared.data.subjects.length}科目・{prepared.data.notes.length}授業・{prepared.pdfs.length}PDF・{prepared.data.strokes.length}ストローク</p><p>{prepared.data.subjects.map(s=>s.name).join('、')}</p><label>復元方法<select aria-label="復元方法" value={mode} disabled={busy} onChange={e=>{setMode(e.target.value as 'merge'|'replace');setConfirm(false);}}><option value="merge">マージ（追加・既存データを保持）</option><option value="replace">上書きして復元</option></select></label><p>{mode==='merge'?'バックアップを別の科目として追加します。同じ科目を再度取り込むと複製になります。':prepared.manifest.scope==='all'?'現在の全データを削除し、このバックアップの内容に置き換えます。':'同じIDの科目と関連データを置き換えます。それ以外の科目は保持します。'}</p>{mode==='replace'&&<label className="restore-confirm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)} disabled={busy}/>置き換えの範囲を確認しました。現在の必要なデータは保存済みです。</label>}<button className={mode==='replace'?'danger':'primary'} disabled={busy||(mode==='replace'&&!confirm)} onClick={()=>void importZip()}>{mode==='replace'?'上書きして復元する':'追加して復元する'}</button></div>}</section>{progress&&<p role="status" className="backup-progress">{progress}</p>}{error&&<p role="alert" className="error">{error}</p>}</dialog></>;
}
